//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIGNACION_ALUMNO
    {
        public int ID_ASIGNACION { get; set; }
        public Nullable<int> ID_SECCION { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<int> NOTA1 { get; set; }
        public Nullable<int> NOTA2 { get; set; }
        public Nullable<int> NOTA3 { get; set; }
    }
}
