//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASISTENCIA_MATERIA
    {
        public int ID_ASISTENCIA { get; set; }
        public Nullable<int> ID_SECCION { get; set; }
        public Nullable<int> ID_CALENDARIOMATERIA { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<int> ASISTENCIA { get; set; }
        public Nullable<int> EXAMEN { get; set; }
    }
}
