//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTACIONAMIENTO
    {
        public int ID_ESTACIONAMIENTO { get; set; }
        public Nullable<int> CUPO { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
    }
}
