//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRO
    {
        public int ID_LIBRO { get; set; }
        public string TITULO { get; set; }
        public string ANO { get; set; }
        public string AUTOR { get; set; }
        public string NUMERO_PAGINA { get; set; }
        public Nullable<int> ID_CATEGORIA { get; set; }
        public string DESCRIPCION { get; set; }
        public string IMAGEN { get; set; }
    }
}
