//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MI_MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MI_MENU()
        {
            this.MI_PERMISOS_MENU = new HashSet<MI_PERMISOS_MENU>();
            this.MI_SUB_MENU = new HashSet<MI_SUB_MENU>();
        }
    
        public int ID_MENU { get; set; }
        public string NOMBRE_MENU { get; set; }
        public Nullable<bool> TIPO { get; set; }
        public string VISTA { get; set; }
        public string CONTROLADOR { get; set; }
        public string ICONO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MI_PERMISOS_MENU> MI_PERMISOS_MENU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MI_SUB_MENU> MI_SUB_MENU { get; set; }
    }
}
