//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MI_SUB_MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MI_SUB_MENU()
        {
            this.MI_PERMISOS_SUB_MENU = new HashSet<MI_PERMISOS_SUB_MENU>();
        }
    
        public int ID_SUB_MODULO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> COD_MODULO { get; set; }
        public string VISTA { get; set; }
        public string CONTROLADOR { get; set; }
    
        public virtual MI_MENU MI_MENU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MI_PERMISOS_SUB_MENU> MI_PERMISOS_SUB_MENU { get; set; }
    }
}
