//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoVisionEntities : DbContext
    {
        public ProyectoVisionEntities()
            : base("name=ProyectoVisionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASIGNACION_ALUMNO> ASIGNACION_ALUMNO { get; set; }
        public virtual DbSet<ASIGNACION_PROFESOR> ASIGNACION_PROFESOR { get; set; }
        public virtual DbSet<ASISTENCIA_MATERIA> ASISTENCIA_MATERIA { get; set; }
        public virtual DbSet<CALENDARIO_MATERIA> CALENDARIO_MATERIA { get; set; }
        public virtual DbSet<CATEGORIA_LIBRO> CATEGORIA_LIBRO { get; set; }
        public virtual DbSet<ESTACIONAMIENTO> ESTACIONAMIENTO { get; set; }
        public virtual DbSet<LIBRO> LIBRO { get; set; }
        public virtual DbSet<MATERIA> MATERIA { get; set; }
        public virtual DbSet<MI_MENU> MI_MENU { get; set; }
        public virtual DbSet<MI_PERMISOS_MENU> MI_PERMISOS_MENU { get; set; }
        public virtual DbSet<MI_PERMISOS_SUB_MENU> MI_PERMISOS_SUB_MENU { get; set; }
        public virtual DbSet<MI_SUB_MENU> MI_SUB_MENU { get; set; }
        public virtual DbSet<MI_TIPO_USUARIOS> MI_TIPO_USUARIOS { get; set; }
        public virtual DbSet<MI_USUARIOS> MI_USUARIOS { get; set; }
        public virtual DbSet<PERIODO> PERIODO { get; set; }
        public virtual DbSet<REGISTRO_BICICLETA> REGISTRO_BICICLETA { get; set; }
        public virtual DbSet<REGISTRO_INGRESO> REGISTRO_INGRESO { get; set; }
        public virtual DbSet<REGISTRO_LIBRO> REGISTRO_LIBRO { get; set; }
        public virtual DbSet<SECCION> SECCION { get; set; }
        public virtual DbSet<SERIELIBRO> SERIELIBRO { get; set; }
        public virtual DbSet<TORNIQUETE> TORNIQUETE { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<ipv6_database_firewall_rules> ipv6_database_firewall_rules { get; set; }
    }
}
