//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_INGRESO
    {
        public long ID_REGISTRO { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHA_HORA_INGRESO { get; set; }
        public Nullable<System.DateTime> FECHA_HORA_SALIDA { get; set; }
        public Nullable<int> ID_TORNIQUETE { get; set; }
    }
}
